Rename `deploy.yml` to `studio.yml`

diff --git a/.github/workflows/studio.yml b/.github/workflows/studio.yml
--- a/.github/workflows/studio.yml
+++ b/.github/workflows/studio.yml
@@ -1,6 +1,6 @@
 
-name: studio-nuxt-build
-run-name: studio nuxt build
+name: studio-nuxt-build-deploy
+run-name: studio nuxt deploy
 
 on:
   # Runs on pushes targeting the default branch
@@ -40,17 +40,10 @@ jobs:
       - name: Identify package manager
         id: pkgman
         run: |
-          cache=`[ -f "./pnpm-lock.yaml" ] && echo "pnpm" || ([ -f "./package-lock.json" ] && echo "npm" || ([ -f "./yarn.lock" ] && echo "yarn" || echo ""))`
+          cache=`([ -f "./package-lock.json" ] && echo "npm" || ([ -f "./yarn.lock" ] && echo "yarn" || echo ""))`
           package_manager=`[ ! -z "$cache" ] && echo "$cache" || echo "pnpm"`
           echo "cache=$cache" >> $GITHUB_OUTPUT
           echo "package_manager=$package_manager" >> $GITHUB_OUTPUT
-
-      - uses: pnpm/action-setup@v2.4.0
-        if: ${{ steps.pkgman.outputs.package_manager == 'pnpm' }}
-        name: Install pnpm
-        id: pnpm-install
-        with:
-          version: 8
 
       - uses: actions/setup-node@v3
         with:
@@ -66,14 +59,23 @@ jobs:
       - name: Create .nuxtrc
         run: echo $'\nautoImport=true\nmodules[]=@nuxthq/studio' >> .nuxtrc
 
+      - name: Check for filenames with spaces in `./public`
+        run: |
+          if find ./public -name "* *" -type f | read; then
+            echo "Error: Filenames with spaces found in ./public folder"
+            exit 1
+          fi
+
       - name: Generate
-        run: npx nuxi build --preset github_pages
+        run: npx nuxi generate
         env:
           NUXT_PUBLIC_STUDIO_API_URL: https://api.nuxt.studio
-          NUXT_PUBLIC_STUDIO_TOKENS: 8459472a79e3659085f9878e9ea99450c47bf7761d62e2f6fbb35fab9332d146
+          NUXT_PUBLIC_STUDIO_TOKENS: f58249cb011ab7f60a0479ec8be44f9bc2d062763e3fb57ca5cc21d016b3307a
 
+      - name: Add .nojekyll file
+        run: touch .output/public/.nojekyll
 
-      # Deployment job
+        # Deployment job
       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@v4
         with:
